# -*- coding: utf-8 -*-
"""Bot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1idt59TkSJmalXHAk50FmlvqYLCrD4yEj
"""

def usuario(): #define la función llamada usuario
    nombre = input("Por favor ingrese su nombre: ") #Crear un espacio de texto para que el usuario responda una pregunta
    print(f"Hola, {nombre}! Encantado de conocerte.") #la f permite que se pueda usar una variable #Imprimir "Hola" + el texto que escrbió el usuario + "Encantado de conocerte"
    print() #Crear un espacio entre los textos
    print(f"¿En qué te puedo ayudar, {nombre}?") #Imprimir un texto diseñado por el creador + el texto que escribió el usuario

usuario() #Hacer correr la función creada